import {useEffect,useState} from "react";
import {createFileRoute,useNavigate} from "@tanstack/react-router";
import {GlassCard} from "@/features/core/ui/GlassCard";
import {listCampaigns,type Campaign} from "@/features/campaigns/api";
import {listCharacters,type Character} from "@/features/characters/api";
import {getSession} from "@/lib/session";
import {supabaseFetch} from "@/lib/supabase";
export const Route=createFileRoute("/campaigns/$id")({component:CampaignDashboard});
function CampaignDashboard(){const {id}=Route.useParams();const nav=useNavigate();const [campaign,setCampaign]=useState<Campaign|null>(null);const [characters,setCharacters]=useState<Character[]>([]);const [members,setMembers]=useState<any[]>([]);const [error,setError]=useState("");const token=getSession()?.access_token;
useEffect(()=>{Promise.all([listCampaigns(),listCharacters(),supabaseFetch("campaign_members?campaign_id=eq."+encodeURIComponent(id)+"&select=* ",{},token)]).then(([cs,chars,ms])=>{setCampaign(cs.find(c=>c.id===id)||null);setCharacters(chars);setMembers(ms)}).catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar."))},[id]);
if(error)return <main className="min-h-screen bg-[#070b14] p-10 text-red-300">{error}</main>;if(!campaign)return <main className="min-h-screen bg-[#070b14] p-10 text-slate-500">Carregando campanha...</main>;
const copy=()=>navigator.clipboard?.writeText(location.origin+"/campaigns/join?code="+campaign.invite_code);
return <main className="min-h-screen bg-[#070b14] px-6 py-10 text-slate-100"><div className="mx-auto max-w-6xl"><button onClick={()=>nav({to:"/campaigns"})} className="text-sm text-slate-500">← Campanhas</button><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.3em] text-violet-300">NEXUS / MESA</p><h1 className="mt-2 text-4xl font-bold">{campaign.name}</h1><p className="mt-2 text-slate-500">{campaign.description||"Sem descrição"}</p></div><button onClick={copy} className="rounded-xl border border-sky-400/20 bg-sky-400/5 px-4 py-3 text-sm text-sky-300">Copiar convite</button></div>
<div className="mt-8 grid gap-5 lg:grid-cols-3"><GlassCard className="p-6 lg:col-span-2"><h2 className="text-lg font-semibold">Personagens disponíveis</h2><div className="mt-4 grid gap-3 md:grid-cols-2">{characters.map(c=><div key={c.id} className="rounded-xl border border-white/10 p-4"><p className="font-semibold">{c.name}</p><p className="text-xs text-slate-500">{c.class_name} · NEX {c.nex}%</p></div>)}</div></GlassCard><GlassCard className="p-6"><h2 className="text-lg font-semibold">Mesa</h2><p className="mt-4 text-3xl font-bold">{members.length}</p><p className="text-xs text-slate-500">membros registrados</p><div className="mt-6 rounded-xl border border-white/10 bg-black/20 p-4"><p className="text-xs text-slate-500">Código de convite</p><p className="mt-2 break-all font-mono text-sm text-sky-300">{campaign.invite_code}</p></div></GlassCard></div>
<GlassCard className="mt-5 p-6"><h2 className="text-lg font-semibold">Sessão</h2><div className="mt-4 grid gap-3 md:grid-cols-3"><button className="rounded-xl border border-white/10 p-4 text-left hover:bg-white/5"><b>Notas</b><p className="mt-1 text-xs text-slate-500">Registrar acontecimentos</p></button><button className="rounded-xl border border-white/10 p-4 text-left hover:bg-white/5"><b>Handouts</b><p className="mt-1 text-xs text-slate-500">Materiais da campanha</p></button><button className="rounded-xl border border-white/10 p-4 text-left hover:bg-white/5"><b>NPCs</b><p className="mt-1 text-xs text-slate-500">Gerenciar personagens do mestre</p></button></div></GlassCard></div></main>}