import {useEffect,useState} from "react";
import {createFileRoute,useNavigate} from "@tanstack/react-router";
import {GlassCard} from "@/features/core/ui/GlassCard";
import {CharacterForm} from "@/features/characters/CharacterForm";
import {listCharacters,updateCharacter,type Character} from "@/features/characters/api";
import {derived,modifier} from "@/features/sheet/derived";
import {DiceRoller} from "@/features/sheet/DiceRoller";
import {ResourceBar} from "@/features/sheet/ResourceBar";
import {ATTRIBUTES} from "@/features/characters/data";
import {SkillPanel} from "@/features/sheet/SkillPanel";
import type {Skill} from "@/features/sheet/skills";
import {InventoryPanel,type InventoryItem} from "@/features/sheet/InventoryPanel";
import {WeaponPanel} from "@/features/sheet/WeaponPanel";
import type {Weapon} from "@/features/sheet/weapons";
import {ConditionsPanel} from "@/features/sheet/ConditionsPanel";
export const Route=createFileRoute("/characters/$id")({component:CharacterEditor});
function CharacterEditor(){const {id}=Route.useParams();const nav=useNavigate();const [character,setCharacter]=useState<Character|null>(null);const [error,setError]=useState("");const [saving,setSaving]=useState(false); const [skills,setSkills]=useState<Skill[]>([]); const [inventory,setInventory]=useState<InventoryItem[]>([]); const [weapons,setWeapons]=useState<Weapon[]>([]);
useEffect(()=>{listCharacters().then(xs=>{const c=xs.find(x=>x.id===id)||null;setCharacter(c);if(c){setSkills((c.skills||[]) as Skill[]);setInventory((c.inventory||[]) as InventoryItem[]);setWeapons((c.weapons||[]) as Weapon[])}}).catch(e=>setError(e instanceof Error?e.message:"Erro ao carregar."))},[id]);
if(error)return <main className="min-h-screen bg-[#070b14] p-10 text-red-300">{error}</main>;
if(!character)return <main className="min-h-screen bg-[#070b14] p-10 text-slate-500">Carregando ficha...</main>;
const attrs=character.attributes||Object.fromEntries(ATTRIBUTES.map(a=>[a,1]));const stats=derived(attrs,character.nex||5);
const skillModifiers:Record<string,number>={Acrobacia:modifier(attrs.AGI||1),Atletismo:modifier(attrs.FOR||1),Fortitude:modifier(attrs.VIG||1),Iniciativa:stats.initiative,Intimidação:modifier(attrs.PRE||1),Investigação:modifier(attrs.INT||1),Luta:modifier(attrs.FOR||1),Ocultismo:modifier(attrs.INT||1),Percepção:modifier(attrs.PRE||1),Pontaria:modifier(attrs.AGI||1),Reflexos:stats.reflexes,Tecnologia:modifier(attrs.INT||1),Vontade:stats.will};
const persistModules=async(nextSkills=skills,nextInventory=inventory,nextWeapons=weapons,nextConditions:string[]=[] )=>{await updateCharacter(id,{skills:nextSkills,inventory:nextInventory,weapons:nextWeapons,conditions:nextConditions} as any)};
const patch=async(data:Partial<Character>)=>{setSaving(true);try{const updated=await updateCharacter(id,data);setCharacter(updated[0]||character)}finally{setSaving(false)}};
return <main className="min-h-screen bg-[#070b14] px-6 py-10 text-slate-100"><div className="mx-auto max-w-6xl"><button onClick={()=>nav({to:"/characters"})} className="text-sm text-slate-500 hover:text-white">← Personagens</button><div className="mt-6 flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs uppercase tracking-[.3em] text-sky-300">NEXUS / FICHA</p><h1 className="mt-2 text-4xl font-bold">{character.name}</h1><p className="mt-2 text-slate-500">{character.class_name} · {character.origin} · NEX {character.nex}%</p></div>{saving&&<span className="text-xs text-sky-300">Salvando...</span>}</div>
<div className="mt-8 grid gap-5 lg:grid-cols-[1fr_320px]"><div className="space-y-5"><GlassCard className="p-6"><div className="grid grid-cols-2 gap-3 sm:grid-cols-5">{ATTRIBUTES.map(a=><div key={a} className="rounded-xl border border-white/10 bg-black/10 p-4 text-center"><p className="text-xs text-slate-500">{a}</p><p className="mt-1 text-2xl font-bold">{attrs[a]||1}</p><p className="text-xs text-sky-300">{modifier(attrs[a]||1)>=0?"+":""}{modifier(attrs[a]||1)}</p></div>)}</div></GlassCard>
<GlassCard className="grid gap-4 p-6 sm:grid-cols-3">{[["Defesa",stats.defense],["Iniciativa",stats.initiative],["Fortitude",stats.fortitude],["Reflexos",stats.reflexes],["Vontade",stats.will],["Movimento",9]].map(([label,value])=><div key={label as string} className="rounded-xl border border-white/10 bg-black/10 p-4"><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-bold text-white">{value}</p></div>)}</GlassCard>
<GlassCard className="space-y-6 p-6"><ResourceBar label="Pontos de Vida" current={character.hp_current??stats.hpMax} max={character.hp_max||stats.hpMax} onChange={v=>setCharacter({...character,hp_current:v})}/><ResourceBar label="Pontos de Esforço" current={character.pe_current??stats.peMax} max={character.pe_max||stats.peMax} onChange={v=>setCharacter({...character,pe_current:v})}/><ResourceBar label="Sanidade" current={character.san_current??stats.sanMax} max={character.san_max||stats.sanMax} onChange={v=>setCharacter({...character,san_current:v})}/><button onClick={()=>patch({hp_current:character.hp_current,pe_current:character.pe_current,san_current:character.san_current})} className="text-xs text-sky-300 hover:text-white">Salvar recursos</button></GlassCard>
<GlassCard className="p-6"><h2 className="mb-4 text-lg font-semibold">Rolagem</h2><DiceRoller/></GlassCard>
<GlassCard className="p-6"><h2 className="mb-5 text-lg font-semibold">Perícias</h2><SkillPanel values={skills} onChange={v=>{setSkills(v);void persistModules(v,inventory,weapons)}} modifiers={skillModifiers}/></GlassCard>
<GlassCard className="p-6"><h2 className="mb-5 text-lg font-semibold">Inventário</h2><InventoryPanel items={inventory} onChange={v=>{setInventory(v);void persistModules(skills,v,weapons)}}/></GlassCard>
<GlassCard className="p-6"><h2 className="mb-5 text-lg font-semibold">Armas</h2><WeaponPanel items={weapons} onChange={v=>{setWeapons(v);void persistModules(skills,inventory,v)}}/></GlassCard>
<GlassCard className="p-6"><h2 className="mb-5 text-lg font-semibold">Condições</h2><ConditionsPanel/></GlassCard>
<GlassCard className="p-6"><h2 className="mb-5 text-lg font-semibold">Dados da ficha</h2><CharacterForm initial={character} submitLabel="Salvar ficha" onSubmit={async data=>patch(data)}/></GlassCard></div>
<aside className="space-y-5"><GlassCard className="p-6"><h2 className="text-lg font-semibold">Resumo</h2><div className="mt-5 space-y-3 text-sm"><p><span className="text-slate-500">Classe</span><br/>{character.class_name||"—"}</p><p><span className="text-slate-500">Origem</span><br/>{character.origin||"—"}</p><p><span className="text-slate-500">NEX</span><br/>{character.nex}%</p><p><span className="text-slate-500">Idade</span><br/>{character.age||"—"}</p></div></GlassCard><GlassCard className="p-6"><h2 className="text-lg font-semibold">Próximo módulo</h2><p className="mt-2 text-sm text-slate-500">Perícias, inventário, armas, rituais e condições serão adicionados à ficha.</p></GlassCard></aside></div></div></main>}